Repository openpcrs/pcrs.beta.gouv.fr, pull requests merged in 2023-10, with the labels that each got.

#312 Réorganisation des dossier `/lib` et `/server`
  backend/__tests__/index.js
  backend/__tests__/projets-validator.js
  backend/__tests__/projets.js
  backend/admin/__tests__/administrators.js
  backend/admin/__tests__/creators-emails.js
  backend/admin/administrators.js
  backend/admin/creators-emails.js
  backend/admin/email-template.js
  backend/admin/reports.js
  backend/auth/middleware.js
  backend/auth/pin-code/email-template.js
  backend/auth/pin-code/index.js
  backend/export/csv.js
  backend/index.js
  backend/lib/calculator.js
  backend/lib/models/projets.js
  backend/lib/projets-validator.js
  backend/lib/territoires.js
  backend/mock/mock-invalid-projet.js
  backend/mock/mock-valid-projet.js
  backend/routes/administrators.js
  backend/routes/auth.js
  backend/routes/calculator.js
  backend/routes/creators-emails.js
  backend/routes/data.js
  backend/routes/projets.js
  backend/routes/report.js
  backend/util/error-handler.js
  backend/util/mongo.js
  backend/util/payload.js
  backend/util/sendmail.js
  backend/util/w.js
  components/map-sidebar/index.js
  jsconfig.json
  lib/suivi-pcrs.js
  package.json
  shared/find-closest-etape.js
Labels: technical-debt

#329 Correction de la validation d’erreur d'un champ nombre
  components/number-input.js
Labels: bug

#326 Reprise du code du formulaire de livrables
  components/date-input.js
  components/suivi-form/acteurs/index.js
  components/suivi-form/index.js
  components/suivi-form/livrables/index.js
  components/suivi-form/livrables/livrable-card.js
  components/suivi-form/livrables/livrable-form.js
  components/suivi-form/livrables/utils/select-options.js
  lib/utils/select-options.js
  reducers/form-reducer.js
Labels: technical-debt

#328 Reprise du formulaire de périmètres
  components/suivi-form/index.js
  components/suivi-form/perimetres/index.js
  components/suivi-form/perimetres/perimetre-form.js
  components/suivi-form/perimetres/perimetre.js
  hooks/input.js
Labels: technical-debt

#332 Reprise du formulaire des subventions
  components/number-input.js
  components/suivi-form/subventions/index.js
  components/suivi-form/subventions/subvention-card.js
  components/suivi-form/subventions/subvention-form.js
  lib/string.js
Labels: technical-debt

#330 Modification du modèle de données et connexion au scanner
  .env.sample
  README.md
  backend/__tests__/projets-validator.js
  backend/__tests__/projets.js
  backend/lib/api-scanner.js
  backend/lib/models/projets.js
  backend/lib/projets-validator.js
  backend/mock/mock-invalid-projet.js
  backend/mock/mock-valid-projet.js
  scripts/migration-v04.js
Labels: do-not-merge
